replicaCount: 1

image:
  repository: kubepattern
  pullPolicy: Always
  tag: "latest"

rbac:
  # Define the RBAC rules for KubePattern (to scan only specific resources, modify accordingly)
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["get", "list", "watch"]

analysis:
  # Save in involved resoureces namespace 
  saveInNamespace: false
  # Default output namespace if option save-in-namespace == false for namespaced resources
  # Default output namespace for cluster scoped resources
  targetNamespace: pattern-analysis-ns # consider using pattern-analysis-ns dedicated namespace
  # Deploy Cronjob
  schedule: false
  # Periodic analysis frequecy es: @hourly
  jobFrequency: "0 * * * *"

patternRegistry:
  orgName: "kubepattern"
  # kubepattern official pattern registry: https://github.com/kubepattern/registry 
  repo:
    branch: "main"
    name: "registry"
    # For private repositories access
    token: ""
