apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubepattern-get-list-watch-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubepattern-get-list-all
subjects:
- kind: ServiceAccount
  name: kubepattern-sa
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubepattern-crd-biding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubepattern-crd
subjects:
- kind: ServiceAccount
  name: kubepattern-sa

  namespace: {{ .Release.Namespace }}
