apiVersion: v1
kind: Secret
metadata:
  name: kubepattern-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Secret to access kubepattern pattern registry repository (if private)
  repository-token: "" # Your Base64 token