apiVersion: v1
kind: Service
metadata:
  name: kubepattern-svc  
  namespace: kubepattern-ns
spec:
  selector:
    app: kubepattern
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 8080