apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: k8spatterns.kubepattern.it
spec:
  group: kubepattern.it
  names:
    plural: k8spatterns
    singular: k8spattern
    kind: K8sPattern
    shortNames:
      - k8sp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - apiVersion
                - name
                - type
              properties:
                apiVersion:
                  type: string
                  description: "Versione interna del pattern (es: v1)."
                name:
                  type: string
                  description: "Nome del pattern (es: Sidecar, Health Probe)."
                type:
                  type: string
                  description: "Categoria generale del pattern (es: Structural, Behavioral)."
                description:
                  type: string
                  description: "Descrizione dettagliata del pattern."
                referenceLink:
                  type: string
                  description: "Link di riferimento alla documentazione."
                message:
                  type: string
                  description: "Messaggio informativo o di raccomandazione."
                severity:
                  type: string
                  description: "Livello di severità (Info, Warning, Critical)."
                  enum:
                    - INFO
                    - WARNING
                    - CRITICAL
                confidence:
                  type: string
                  description: "Livello di confidenza nell'individuazione del pattern. (LOW < 40, MEDIUM 40-70, HIGH > 70)."
                  enum:
                    - LOW
                    - MEDIUM
                    - HIGH
                category:
                  type: string
                  description: "Categoria di applicazione (Reliability, Security, Performance)."
                  enum:
                    - Reliability
                    - Security
                    - Performance
                suppress:
                  type: boolean
                  description: "Soppresso perchè falso positivo."
                scores:
                  type: array
                  description: "Array dei punteggi dei vari controlli."
                  items:
                    type: object
                    required:
                      - category
                      - score
                    properties:
                      category:
                        type: string
                        description: "Nome della categoria/filtro del controllo."
                      score:
                        type: integer
                        description: "Punteggio su 100."
                        minimum: 0
                        maximum: 100
                resources:
                  type: array
                  description: "Array delle risorse Kubernetes coinvolte nel pattern."
                  items:
                    type: object
                    required:
                      - name
                      - role
                      - uid
                    properties:
                      name:
                        type: string
                        description: "Nome della risorsa Kubernetes."
                      namespace:
                        type: string
                        description: "Namespace della risorsa Kubernetes."
                      role:
                        type: string
                        description: "Ruolo nel Pattern Kubernetes"
                      uid:
                        type: string
                        description: "UID della risorsa Kubernetes."
