apiVersion: v1
kind: Namespace
metadata:
  name: kubepattern-ns
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: pattern-analysis-ns
spec: {}
status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubepattern-get-list-all
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubepattern-create-crd
rules:
- apiGroups: ["kubepattern.it"]
  resources: ["k8spatterns"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubepattern-get-list-all
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubepattern-get-list-all
subjects:
- kind: ServiceAccount
  name: kubepattern-sa
  namespace: kubepattern-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubepattern-create-crd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubepattern-create-crd
subjects:
- kind: ServiceAccount
  name: kubepattern-sa
  namespace: kubepattern-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubepattern-sa
  namespace: kubepattern-ns
---
apiVersion: v1
kind: Service
metadata:
  name: kubepattern-svc  
  namespace: kubepattern-ns
spec:
  selector:
    app: kubepattern
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubepattern
  name: kubepattern
  namespace: kubepattern-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubepattern
  template:
    metadata:
      labels:
        app: kubepattern
      annotations:
        # Reload the pod if the ConfigMap changes
        checksum/config: ${{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: kubepattern-sa
      containers:
      - image: ghcr.io/kubepattern/kubepattern:latest
        imagePullPolicy: Always
        name: kpattern
        # 1. Inject the Secret as an environment variable
        env:
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: kubepattern-secret
              key: repository-token
        # 2. Specify to Spring where to find the mounted file (optional but recommended)
        args: ["--spring.config.location=file:/config/application.properties"]
        # 3. Mount the volume at the chosen path
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
      
      # 4. Define the volume based on the ConfigMap
      volumes:
      - name: config-volume
        configMap:
          name: kubepattern-config
      
      restartPolicy: Always
---
#apiVersion: batch/v1
#kind: CronJob
#metadata:
#  name: kubepattern-periodic-cluster-analysis
#  namespace: kubepattern-ns
#spec:
#  schedule: "*/1 * * * *" # It runs every minute for demonstration;
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          containers:
#          - name: api-caller
#            image: curlimages/curl:latest
#            imagePullPolicy: IfNotPresent
#            command:
#            - /bin/sh
#            - -c
#            - |
#              echo "Request periodic cluster analysis:"
#              curl -v http://kubepattern-svc/analysis/cluster
#          restartPolicy: OnFailure

#kubectl create secret docker-registry gcr-key \
#  --namespace=kubepattern-ns \
#  --docker-server=europe-west1-docker.pkg.dev \
#  --docker-username=oauth2accesstoken \
#  --docker-password=$(gcloud auth print-access-token)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubepattern-config
  namespace: kubepattern-ns
data:
  application.properties: |
    app.report.save-in-namespace=false
    app.report.target-namespace=pattern-analysis-ns
    app.pattern-registry.organization-name=kubepattern
    app.pattern-registry.repository-branch=main
    app.pattern-registry.repository-name=registry

---
apiVersion: v1
kind: Secret
metadata:
  name: kubepattern-secret
  namespace: kubepattern-ns
type: Opaque
data:
  # Secret to access kubepattern pattern registry repository (if private)
  repository-token: "" # Your Base64 token